services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pragneshanekal/agent-langgraph:url_update
    env_file:
      - .env
    ports:
      - "8000:8000"  # FastAPI port
      - "8501:8501"  # Streamlit port
      - "9090:9090" # Codelabs port
    command: >
      /bin/bash -c "uvicorn fast_api.fastapi_setup:app --host 0.0.0.0 --port 8000 --reload &
      streamlit run streamlit_app.py --server.port 8501"
    volumes:
      - .:/code